included:
  - Package.swift
  - Sources
  - Tests

excluded:
  - .build
  - .git
  - .github
  - .swiftpm
  - Sources/AstroCore/Planets/VSOP87DData
  - Sources/AstroCoreLocations/Resources

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - non_optional_string_data_conversion
  - opening_brace
  - superfluous_disable_command
  - todo
  - trailing_comma
  - type_body_length

function_parameter_count:
  warning: 8
  error: 10
