import Foundation

/// Per-planet residual corrections fitted against JPL Horizons (DE440)
/// Generated by fit_planet_residuals.py — do not edit manually
enum PlanetResiduals {
    private struct Term {
        let amplitude: Double // arcseconds
        let frequency: Double // cycles per Julian century
        let phase: Double // radians
    }

    /// Apply residual correction for a planet.
    /// t: Julian centuries from J2000.0 in TT.
    /// Returns correction in arcseconds.
    static func correctionArcsec(for body: CelestialBody, t: Double) -> Double {
        let terms: [Term]
        switch body {
        case .mercury: terms = mercuryTerms
        case .venus: terms = venusTerms
        case .mars: terms = marsTerms
        case .jupiter: terms = jupiterTerms
        case .saturn: terms = saturnTerms
        default: return 0.0
        }
        var total = 0.0
        for term in terms {
            total += term.amplitude * Foundation.sin(
                2.0 * .pi * term.frequency * t + term.phase
            )
        }
        return total
    }

    // swiftlint:disable comma line_length
    private static let mercuryTerms: [Term] = [
        Term(amplitude: 0.3269714991, frequency: 0.3978871012, phase: -0.1291443299),
        Term(amplitude: 0.2107398676, frequency: 0.7957742023, phase: -2.2549451108),
        Term(amplitude: 0.1793117937, frequency: 17.1091453504, phase: 2.0072117340),
        Term(amplitude: 0.1554924996, frequency: 16.7112582493, phase: -2.3645765487),
        Term(amplitude: 0.1413230490, frequency: 1.1936613035, phase: 1.6011219489),
        Term(amplitude: 0.1397145362, frequency: 17.5070324516, phase: -0.1432785722),
        Term(amplitude: 0.1345048170, frequency: 16.3133711481, phase: -0.5121912958),
        Term(amplitude: 0.1107552954, frequency: 15.9154840469, phase: 1.4790520565),
        Term(amplitude: 0.0920675889, frequency: 1.5915484047, phase: -0.9389090819),
        Term(amplitude: 0.0816715943, frequency: 1.9894355059, phase: 2.7724893332),
        Term(amplitude: 0.0787531874, frequency: 17.9049195528, phase: -2.3912749018),
        Term(amplitude: 0.0708662840, frequency: 15.5175969457, phase: -2.4750083571),
        Term(amplitude: 0.0705980677, frequency: 2.3873226070, phase: 0.3673132151),
        Term(amplitude: 0.0682439391, frequency: 33.8204035997, phase: 1.2237921560),
        Term(amplitude: 0.0631217569, frequency: 33.4225164985, phase: -3.0073997354),
        Term(amplitude: 0.0580908441, frequency: 2.7852097082, phase: -2.2389378339),
        Term(amplitude: 0.0515931650, frequency: 3.1830968094, phase: 1.5012683843),
        Term(amplitude: 0.0509003816, frequency: 15.1197098446, phase: 0.1804172268),
        Term(amplitude: 0.0506511270, frequency: 3.5809839106, phase: -1.0186955349)
    ]
    // swiftlint:enable comma line_length

    // swiftlint:disable comma line_length
    private static let venusTerms: [Term] = [
        Term(amplitude: 0.3196878463, frequency: 0.3978871012, phase: -0.0995885755),
        Term(amplitude: 0.2044256492, frequency: 0.7957742023, phase: -2.2180289123),
        Term(amplitude: 0.1411871795, frequency: 1.1936613035, phase: 1.6769708362),
        Term(amplitude: 0.0923457416, frequency: 1.5915484047, phase: -0.7926823870),
        Term(amplitude: 0.0792408545, frequency: 1.9894355059, phase: 2.9020688273),
        Term(amplitude: 0.0686140187, frequency: 2.3873226070, phase: 0.5022801465),
        Term(amplitude: 0.0656352470, frequency: 62.8661619853, phase: -1.5294725817),
        Term(amplitude: 0.0567138007, frequency: 2.7852097082, phase: -2.0318541678),
        Term(amplitude: 0.0557763939, frequency: 62.4682748841, phase: 0.3818036161),
        Term(amplitude: 0.0551257378, frequency: 63.2640490864, phase: 2.6231162539)
    ]
    // swiftlint:enable comma line_length

    // swiftlint:disable comma line_length
    private static let marsTerms: [Term] = [
        Term(amplitude: 0.1939957993, frequency: 0.3978871012, phase: 0.1046766396),
        Term(amplitude: 0.1086077551, frequency: 0.7957742023, phase: -2.0663772851),
        Term(amplitude: 0.0770808794, frequency: 1.1936613035, phase: 1.6873886260),
        Term(amplitude: 0.0519127055, frequency: 1.5915484047, phase: -0.7476026478)
    ]
    // swiftlint:enable comma line_length

    // swiftlint:disable comma line_length
    private static let jupiterTerms: [Term] = [
        Term(amplitude: 0.2899715475, frequency: 0.3978871012, phase: 0.4728912703),
        Term(amplitude: 0.1175550128, frequency: 0.7957742023, phase: -1.8387402180),
        Term(amplitude: 0.0838505408, frequency: 1.1936613035, phase: 1.7570923692),
        Term(amplitude: 0.0595086682, frequency: 1.9894355059, phase: 3.0080768378),
        Term(amplitude: 0.0505956734, frequency: 1.5915484047, phase: -0.3899690161)
    ]
    // swiftlint:enable comma line_length

    // swiftlint:disable comma line_length
    private static let saturnTerms: [Term] = [
        Term(amplitude: 0.2373242105, frequency: 0.3978871012, phase: 0.5560759318),
        Term(amplitude: 0.0875302804, frequency: 0.7957742023, phase: -1.7078861881),
        Term(amplitude: 0.0655686080, frequency: 3.5809839106, phase: -1.1553962722),
        Term(amplitude: 0.0573881261, frequency: 1.1936613035, phase: 1.9355406349)
    ]
    // swiftlint:enable comma line_length
}
